# -*- coding: utf-8 -*-

DISAMBIGUATION_NAMES = [
    {"locale": "af", "country": "Afrikaans", "string": u"dubbelsinnigheidsbladsy"},
    {"locale": "ar", "country": "Arabic", "string": u'توضيح'},
    {"locale": "be", "country": "Belarusian", "string": u"неадназначнасці"},
    {"locale": "bg", "country": "Bulgarian", "string": u"пояснение"},
    {"locale": "bn", "country": "Bengali", "string": u"দ্ব্যর্থতা নিরসন"},
    {"locale": "bs", "country": "Bosnian", "string": u"razvrstavanje"},
    {"locale": "ca", "country": "Catalan", "string": u"desambiguació"},
    {"locale": "cs", "country": "Czech", "string": u"rozcestník"},
    {"locale": "cy", "country": "Welsh", "string": u"gwahaniaethu"},
    {"locale": "da", "country": "Danish", "string": u"flertydig"},
    {"locale": "de", "country": "German", "string": u"Begriffsklärung"},
    {"locale": "el", "country": "Greek", "string": u"αποσαφήνιση"},
    {"locale": "en", "country": "English", "string": u"disambiguation"},
    {"locale": "eo", "country": "Esperanto", "string": u"disambiguation"},
    {"locale": "es", "country": "Spanish", "string": u"desambiguación"},
    {"locale": "et", "country": "Estonian", "string": u"täpsustus"},
    {"locale": "eu", "country": "Basque", "string": u"argipen"},
    {"locale": "fa", "country": "Persian", "string": u"ابهامزدایی"},
    {"locale": "fi", "country": "Finnish", "string": u"täsmennyssivu"},
    {"locale": "fr", "country": "French", "string": u"homonymie"},
    {"locale": "gu", "country": "Gujarati", "string": u"સંદિગ્ધ વાક્યો વાળા"},
    {"locale": "hi", "country": "Hindi", "string": u"बहुविकल्पी"},
    {"locale": "hr", "country": "Croatian", "string": u"razdvojbena"},
    {"locale": "ht", "country": "Haitian Creole", "string": u"menm non"},
    {"locale": "hu", "country": "Hungarian", "string": u"egyértelműsítő"},
    {"locale": "hy", "country": "Armenian", "string": u"Տարբերման"},
    {"locale": "id", "country": "Indonesian", "string": u"disambiguasi"},
    {"locale": "is", "country": "Icelandic", "string": u"aðgreining"},
    {"locale": "it", "country": "Italian", "string": u"disambiguazione"},
    {"locale": "iw", "country": "Hebrew", "string": u"פירושונים"},
    {"locale": "ja", "country": "Japanese", "string": u"曖昧性解消"},
    {"locale": "jw", "country": "Javanese", "string": u"disambiguasi"},
    {"locale": "ka", "country": "Georgian", "string": u"მრავალმნიშვნელოვანი"},
    {"locale": "kk", "country": "Kazakh", "string": u"айрықты"},
    {"locale": "km", "country": "Khmer", "string": u"ពាក្យស្រដៀងគ្នា"},
    {"locale": "kn", "country": "Kannada", "string": u"ದ್ವಂದ್ವ ನಿವಾರಣೆ"},
    {"locale": "ko", "country": "Korean", "string": u"동음"},
    {"locale": "la", "country": "Latin", "string": u"discretiva"},
    {"locale": "lt", "country": "Lithuanian", "string": u"nuorodiniame"},
    {"locale": "lv", "country": "Latvian", "string": u"Neskaidrību"},
    {"locale": "mg", "country": "Malagasy", "string": u"ampy"},
    {"locale": "mk", "country": "Macedonian", "string": u"појаснување"},
    {"locale": "ml", "country": "Malayalam", "string": u"വിവക്ഷകൾ"},
    {"locale": "mr", "country": "Marathi", "string": u"संदिग्धकरण नि:"},
    {"locale": "ms", "country": "Malay", "string": u"nyahkekaburan"},
    {"locale": "mt", "country": "Maltese", "string": u"diżambigwazzjoni"},
    {"locale": "my", "country": "Myanmar (Burmese)", "string": u"ကျိုးပျက်နေသောဖိုင်လင့်များပါသည့်"},
    {"locale": "ne", "country": "Nepali", "string": u"डिस्एम्बिगुएसन"},
    {"locale": "nl", "country": "Dutch", "string": u"ondubbelzinnig"},
    {"locale": "no", "country": "Norwegian", "string": u"andre betydninger"},
    {"locale": "pa", "country": "Punjabi", "string": u"ਸਪੱਸ਼ਟਤਾ"},
    {"locale": "pl", "country": "Polish", "string": u"ujednoznacznienie"},
    {"locale": "pt", "country": "Portuguese", "string": u"desambiguação"},
    {"locale": "ro", "country": "Romanian", "string": u"dezambiguizare"},
    {"locale": "ru", "country": "Russian", "string": u"неоднозначности"},
    {"locale": "si", "country": "Sinhala", "string": u"වක්රෝත්තිහරණය"},
    {"locale": "sk", "country": "Slovak", "string": u"rozcestník"},
    {"locale": "sl", "country": "Slovenian", "string": u"razločitev"},
    {"locale": "sq", "country": "Albanian", "string": u"kthjellim"},
    {"locale": "sr", "country": "Serbian", "string": u"Дисамбигуатион"},
    {"locale": "su", "country": "Sundanese", "string": u"disambiguasi"},
    {"locale": "sv", "country": "Swedish", "string": u"olika betydelser"},
    {"locale": "ta", "country": "Tamil", "string": u"ஐயமகற்றல்"},
    {"locale": "te", "country": "Telugu", "string": u"అయోమయ నివృత్తి"},
    {"locale": "tg", "country": "Tajik", "string": u"чопӣ"},
    {"locale": "th", "country": "Thai", "string": u"วิกิพีเดีย"},
    {"locale": "tl", "country": "Filipino", "string": u"paglilinaw"},
    {"locale": "tr", "country": "Turkish", "string": u"anlam ayrımı"},
    {"locale": "uk", "country": "Ukrainian", "string": u"неоднозначності"},
    {"locale": "ur", "country": "Urdu", "string": u"دسمبگاشن"},
    {"locale": "vi", "country": "Vietnamese", "string": u"định hướng"},
    {"locale": "yi", "country": "Yiddish", "string": u"דיסאַמביגואַטיאָן"},
    {"locale": "yo", "country": "Yoruba", "string": u"ìṣeojútùú"},
    {"locale": "zh", "country": "Chinese", "string": u"解疑"}
]
